
export const currencies = [
  { currency: 'USD', symbol: '$', locale: 'en-US' },
  { currency: 'PKR', symbol: 'RS', locale: 'en-US' },
  { currency: 'SAR', symbol: 'SR', locale: 'en-SA' },
  { currency: 'EUR', symbol: '€', locale: 'en-EU' },
  { currency: 'GBP', symbol: '£', locale: 'en-GB' },
  { currency: 'NZD', symbol: 'NZ$', locale: 'en-NZ' },
  { currency: 'AUD', symbol: 'A$', locale: 'en-AU' },
  { currency: 'BGN', symbol: 'лв', locale: 'bg-BG' },
  { currency: 'BRL', symbol: 'R$', locale: 'pt-BR' },
  { currency: 'CAD', symbol: 'C$', locale: 'en-CA' },
  { currency: 'CHF', symbol: 'CHF', locale: 'de-CH' },
  { currency: 'CNY', symbol: '¥', locale: 'zh-CN' },
  { currency: 'CZK', symbol: 'Kč', locale: 'cs-CZ' },
  { currency: 'DKK', symbol: 'kr', locale: 'da-DK' },
  { currency: 'HKD', symbol: 'HK$', locale: 'en-HK' },
  { currency: 'HUF', symbol: 'Ft', locale: 'hu-HU' },
  { currency: 'IDR', symbol: 'Rp', locale: 'id-ID' },
  { currency: 'ILS', symbol: '₪', locale: 'he-IL' },
  { currency: 'INR', symbol: '₹', locale: 'en-IN' },
  { currency: 'ISK', symbol: 'kr', locale: 'is-IS' },
  { currency: 'JPY', symbol: '¥', locale: 'ja-JP' },
  { currency: 'KRW', symbol: '₩', locale: 'ko-KR' },
  { currency: 'MXN', symbol: 'MX$', locale: 'es-MX' },
  { currency: 'MYR', symbol: 'RM', locale: 'ms-MY' },
  { currency: 'NOK', symbol: 'kr', locale: 'no-NO' },
  { currency: 'PHP', symbol: '₱', locale: 'en-PH' },
  { currency: 'PLN', symbol: 'zł', locale: 'pl-PL' },
  { currency: 'RON', symbol: 'lei', locale: 'ro-RO' },
  { currency: 'SEK', symbol: 'kr', locale: 'sv-SE' },
  { currency: 'SGD', symbol: 'S$', locale: 'en-SG' },
  { currency: 'THB', symbol: '฿', locale: 'th-TH' },
  { currency: 'TRY', symbol: '₺', locale: 'tr-TR' },
  { currency: 'ZAR', symbol: 'R', locale: 'en-ZA' },
];
